"""Shared domain primitives for the AI Knowledge Platform."""

from akp_core.errors import (
    AppError,
    BadRequestError,
    BudgetExceededError,
    ConflictError,
    DependencyFailureError,
    EncryptionError,
    ErrorCode,
    FeatureDisabledError,
    ForbiddenError,
    IdempotencyConflictError,
    InsufficientScopeError,
    InternalError,
    MfaInvalidError,
    MfaRequiredError,
    NotFoundError,
    PromptInjectionError,
    QuotaExceededError,
    RateLimitError,
    SerializedError,
    ServiceUnavailableError,
    UnauthorizedError,
    ValidationError,
    to_app_error,
)
from akp_core.ids import IdPrefix, is_id, new_id

__all__ = [
    "AppError",
    "BadRequestError",
    "BudgetExceededError",
    "ConflictError",
    "DependencyFailureError",
    "EncryptionError",
    "ErrorCode",
    "FeatureDisabledError",
    "ForbiddenError",
    "IdPrefix",
    "IdempotencyConflictError",
    "InsufficientScopeError",
    "InternalError",
    "MfaInvalidError",
    "MfaRequiredError",
    "NotFoundError",
    "PromptInjectionError",
    "QuotaExceededError",
    "RateLimitError",
    "SerializedError",
    "ServiceUnavailableError",
    "UnauthorizedError",
    "ValidationError",
    "is_id",
    "new_id",
    "to_app_error",
]
